# Generated by Django 5.2.3 on 2025-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers_app', '0002_answers_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='selected_option',
            field=models.IntegerField(null=True),
        ),
    ]
