# Generated by Django 5.2.3 on 2025-07-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers_app', '0003_answers_score_answers_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
    ]
